[package]
name = "image-histogram"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.1"
csv = "1.1"
plotters = "0.3"
fast-float = "0.2"